language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.5
  - 5.6

install:
  - composer install

script: vendor/bin/phpspec run

after_script: vendor/bin/coveralls -v
